sudo: required
services:
  - docker

before_install:
  - docker build -t foieringserjo/docker-examples -f Dockerfile.dev .

script:
  - docker run -e CI=true foieringserjo/docker-examples npm run test
